---
- name:  Ansible register variable basic example
  hosts: web
  tasks:
    - debug:
        msg: "hello"

- name:  Ansible register variable basic example
  hosts: web
  tasks:
  - name: install
    yum: name={{ item }} state=installed
    with_items:
      - wireshark
      - unzip
      - vim
...
